TEAMS_DICT = {
    "Kansas Jayhawks": "Kansas",
    "Indiana St Sycamores": "Indiana St.",
    "Syracuse Orange": "Syracuse",
    "Cleveland St Vikings": "Cleveland St.",
    "Rutgers Scarlet Knights": "Rutgers",
    "La Salle Explorers": "La Salle",
    "UMKC Kangaroos": "UMKC",
    "Butler Bulldogs": "Butler",
    "Michigan Wolverines": "Michigan",
    "Buffalo Bulls": "Buffalo",
    "North Carolina Tar Heels": "North Carolina",
    "Oklahoma St Cowboys": "Oklahoma St.",
    "Gonzaga Bulldogs": "Gonzaga",
    "Evansville Purple Aces": "Evansville",
    "UMBC Retrievers": "UMBC",
    "Arkansas-Pine Bluff Golden Lions": "Arkansas Pine Bluff",
    "UConn Huskies": "Connecticut",
    "Indiana Hoosiers": "Indiana",
    "Grand Canyon Antelopes": "Grand Canyon",
    "Morgan St Bears": "Morgan St.",
    "Southern Utah Thunderbirds": "Southern Utah",
    "Cornell Big Red": "Cornell",
    "South Dakota St Jackrabbits": "South Dakota St",
    "Stony Brook Seawolves": "Stony Brook",
    "Northern Illinois Huskies": "Northern Illinois",
    "Stonehill Skyhawks": "Stonehill",
    "Washington Huskies": "Washington",
    "Utah Utes": "Utah",
    "Idaho State Bengals": "Idaho St.",
    "Mercer Bears": "Mercer",
    "Baylor Bears": "Baylor",
    "Pacific Tigers": "Pacific",
    "Loyola (Chi) Ramblers": "Loyola Chicago",
    "San Diego St Aztecs": "San Diego St.",
    "Loyola (MD) Greyhounds": "Loyola MD",
    "Southern Illinois Salukis": "Southern Illinois",
    "Seton Hall Pirates": "Seton Hall",
    "North Texas Mean Green": "North Texas",
    "Saint Mary's Gaels": "Saint Mary's",
    "Fresno St Bulldogs": "Fresno St.",
    "BYU Cougars": "BYU",
    "Kent State Golden Flashes": "Kent St.",
    "Tulsa Golden Hurricane": "Tulsa",
    "Montana St Bobcats": "Montana St.",
    "South Alabama Jaguars": "South Alabama",
    "Wake Forest Demon Deacons": "Wake Forest",
    "Idaho Vandals": "Idaho",
    "Boise State Broncos": "Boise St.",
    "Siena Saints": "Siena",
    "Jacksonville Dolphins": "Jacksonville",
    "Presbyterian Blue Hose": "Presbyterian",
    "St. Bonaventure Bonnies": "St. Bonaventure",
    "Fordham Rams": "Fordham",
    "Ohio State Buckeyes": "Ohio St.",
    "Miami Hurricanes": "Miami FL",
    "VCU Rams": "VCU",
    "Saint Louis Billikens": "Saint Louis",
    "Canisius Golden Griffins": "Canisius",
    "Campbell Fighting Camels": "Campbell",
    "Towson Tigers": "Towson",
    "Maryland-Eastern Shore Hawks": "Maryland Eastern Shore",
    "Clemson Tigers": "Clemson",
    "Coppin St Eagles": "Coppin St.",
    "Davidson Wildcats": "Davidson",
    "Saint Joseph's Hawks": "Saint Joseph's",
    "Omaha Mavericks": "Nebraska Omaha",
    "William & Mary Tribe": "William & Mary",
    "Lipscomb Bisons": "Lipscomb",
    "Youngstown St Penguins": "Youngstown St.",
    "Iona Gaels": "Iona",
    "Houston Cougars": "Houston",
    "Maryland Terrapins": "Maryland",
    "Vermont Catamounts": "Vermont",
    "Northern Arizona Lumberjacks": "Northern Arizona",
    "Dartmouth Big Green": "Dartmouth",
    "Texas Longhorns": "Texas",
    "Southern Indiana Screaming Eagles": "Southern Indiana",
    "St. Thomas (MN) Tommies": "St. Thomas",
    "Belmont Bruins": "Belmont",
    "Marshall Thundering Herd": "Marshall",
    "South Carolina Gamecocks": "South Carolina",
    "Penn State Nittany Lions": "Penn St.",
    "Miami (OH) RedHawks": "Miami OH",
    "Ball State Cardinals": "Ball St.",
    "Brown Bears": "Brown",
    "Hofstra Pride": "Hofstra",
    "Gardner-Webb Bulldogs": "Gardner Webb",
    "Illinois St Redbirds": "Illinois St.",
    "UCF Knights": "UCF",
    "Old Dominion Monarchs": "Old Dominion",
    "Drake Bulldogs": "Drake",
    "New Hampshire Wildcats": "New Hampshire",
    "Rice Owls": "Rice",
    "St. John's Red Storm": "St. John's",
    "Rhode Island Rams": "Rhode Island",
    "Vanderbilt Commodores": "Vanderbilt",
    "Ohio Bobcats": "Ohio",
    "Central Michigan Chippewas": "Central Michigan",
    "Milwaukee Panthers": "Milwaukee",
    "Texas A&M-CC Islanders": "Texas A&M Corpus Chris",
    "Niagara Purple Eagles": "Niagara",
    "Fort Wayne Mastodons": "Purdue Fort Wayne",
    "NJIT Highlanders": "NJIT",
    "NC State Wolfpack": "N.C. State",
    "Memphis Tigers": "Memphis",
    "Richmond Spiders": "Richmond",
    "Texas Tech Red Raiders": "Texas Tech",
    "Abilene Christian Wildcats": "Abilene Christian",
    "SIU-Edwardsville Cougars": "SIU Edwardsville",
    "Yale Bulldogs": "Yale",
    "LIU Sharks": "LIU",
    "Boston Univ. Terriers": "Boston University",
    "Wofford Terriers": "Wofford",
    "Sacred Heart Pioneers": "Sacred Heart",
    "Massachusetts Minutemen": "Massachusetts",
    "Toledo Rockets": "Toledo",
    "Robert Morris Colonials": "Robert Morris",
    "Green Bay Phoenix": "Green Bay",
    "Northern Kentucky Norse": "Northern Kentucky",
    "Northern Iowa Panthers": "Northern Iowa",
    "Northeastern Huskies": "Northeastern",
    "Maine Black Bears": "Maine",
    "Marquette Golden Eagles": "Marquette",
    "Duquesne Dukes": "Duquesne",
    "UT Rio Grande Valley Vaqueros": "UT Rio Grande Valley",
    "Valparaiso Beacons": "Valparaiso",
    "Oakland Golden Grizzlies": "Oakland",
    "Wagner Seahawks": "Wagner",
    "Detroit Mercy Titans": "Detroit Mercy",
    "San Francisco Dons": "San Francisco",
    "Fairfield Stags": "Fairfield",
    "American Eagles": "American",
    "Florida A&M Rattlers": "Florida A&M",
    "Bryant Bulldogs": "Bryant",
    "Texas A&M Aggies": "Texas A&M",
    "Nevada Wolf Pack": "Nevada",
    "Colorado St Rams": "Colorado St.",
    "Cal Baptist Lancers": "Cal Baptist",
    "Dayton Flyers": "Dayton",
    "SMU Mustangs": "SMU",
    "UC Santa Barbara Gauchos": "UC Santa Barbara",
    "Utah State Aggies": "Utah St.",
    "West Virginia Mountaineers": "West Virginia",
    "UC Davis Aggies": "UC Davis",
    "DePaul Blue Demons": "DePaul",
    "Arizona St Sun Devils": "Arizona St.",
    "Nebraska Cornhuskers": "Nebraska",
    "San Diego Toreros": "San Diego",
    "Washington St Cougars": "Washington St.",
    "Pepperdine Waves": "Pepperdine",
    "New Mexico Lobos": "New Mexico",
    "UC Riverside Highlanders": "UC Riverside",
    "Denver Pioneers": "Denver",
    "UNLV Rebels": "UNLV",
    "Pittsburgh Panthers": "Pittsburgh",
    "CSU Fullerton Titans": "Cal St. Fullerton",
    "Utah Tech Trailblazers": "Utah Tech",
    "Minnesota Golden Gophers": "Minnesota",
    "UNC Greensboro Spartans": "UNC Greensboro",
    "Eastern Kentucky Colonels": "Eastern Kentucky",
    "Iowa State Cyclones": "Iowa St.",
    "Iowa Hawkeyes": "Iowa",
    'Eastern Illinois Panthers': "Eastern Illinois",
    'IUPUI Jaguars': "IUPUI",
    'North Dakota St Bison': "North Dakota St.",
    'Portland Pilots': "Portland",
    'Central Arkansas Bears': "Central Arkansas",
    'Arkansas-Little Rock Trojans': "Little Rock",
    'Harvard Crimson': "Harvard",
    'Army Knights': "Army",
    'Boston College Eagles': "Boston College",
    'Holy Cross Crusaders': "Holy Cross",
    "Saint Peter's Peacocks": "Saint Peter's",
    'Manhattan Jaspers': "Manhattan",
    'Fairleigh Dickinson Knights': "Fairleigh Dickinson",
    'High Point Panthers': "High Point",
    'North Carolina A&T Aggies': "North Carolina A&T",
    'Quinnipiac Bobcats': "Quinnipiac",
    'Navy Midshipmen': "Navy",
    'Rider Broncs': "Rider",
    'Mississippi St Bulldogs': "Mississippi St.",
    'Tulane Green Wave': "Tulane",
    'California Golden Bears': "California",
    'Florida Gulf Coast Eagles': "Florida Gulf Coast",
    'Tennessee Volunteers': "Tennessee",
    'Illinois Fighting Illini': "Illinois",
    'Kentucky Wildcats': "Kentucky",
    'Pennsylvania Quakers': "Penn",
    'UMass Lowell River Hawks': "UMass Lowell",
    'Virginia Tech Hokies': "Virginia Tech",
    'Troy Trojans': "Troy",
    'Purdue Boilermakers': "Purdue",
    'Alabama Crimson Tide': "Alabama",
    "LSU Tigers": "LSU",
    'Kansas St Wildcats': "Kansas St.",
    'South Carolina St Bulldogs': "South Carolina St.",
    'Bethune-Cookman Wildcats': "Bethune Cookman",
    'Binghamton Bearcats': "Binghamton",
    'Le Moyne Dolphins': "Le Moyne",
    'Central Connecticut St Blue Devils': "Central Connecticut",
    'Creighton Bluejays': "Creighton",
    'Coastal Carolina Chanticleers': "Coastal Carolina",
    'Colgate Raiders': "Colgate",
    'Louisville Cardinals': "Louisville",
    'North Florida Ospreys': "North Florida",
    'Georgia Southern Eagles': "Georgia Southern",
    'Liberty Flames': "Liberty",
    'Monmouth Hawks': "Monmouth",
    'Duke Blue Devils': "Duke",
    'Charlotte 49ers': "Charlotte",
    'Houston Baptist Huskies': "Houston Christian",
    'Louisiana Tech Bulldogs': "Louisiana Tech",
    "Louisiana Ragin' Cajuns": "Louisiana",
    'Southern Miss Golden Eagles': "Southern Miss",
    'Northwestern St Demons': "Northwestern St.",
    "Arizona Wildcats": "Arizona",
    'Wisconsin Badgers': "Wisconsin",
    'Georgia Tech Yellow Jackets': "Georgia Tech",
    'Alabama A&M Bulldogs': "Alabama A&M",
    'Oklahoma Sooners': "Oklahoma",
    'Arkansas Razorbacks': "Arkansas",
    'Marist Red Foxes': "Marist",
    "Drexel Dragons": "Drexel",
    'Florida Gators': "Florida",
    'Jackson St Tigers': "Jackson St.",
    'Western Carolina Catamounts': "Western Carolina",
    'UNC Asheville Bulldogs': "UNC Asheville",
    'Radford Highlanders': "Radford",
    'North Carolina Central Eagles': "North Carolina Central",
    'Santa Clara Broncos': "Santa Clara",
    'San José St Spartans': "San Jose St.",
    'New Orleans Privateers': "New Orleans",
    'Oregon St Beavers': 'Oregon St.',
    'Utah Valley Wolverines': 'Utah Valley',
    'Missouri Tigers': 'Missouri',
    'Air Force Falcons': 'Air Force',
    'Eastern Washington Eagles': 'Eastern Washington',
    'George Washington Colonials': 'George Washington',
    'Southern Jaguars': 'Southern',
    'SE Louisiana Lions': "Southeastern Louisiana",
    'TCU Horned Frogs': "TCU",
    'Sacramento St Hornets': "Sacramento St.",
    'Providence Friars': "Providence",
    'Prairie View Panthers': "Prairie View A&M",
    'Princeton Tigers': "Princeton",
    'Alcorn St Braves': "Alcorn St.",
    'Charleston Cougars': "Charleston",
    'Colorado Buffaloes': "Colorado",
    'Northwestern Wildcats': "Northwestern",
    'North Alabama Lions': "North Alabama",
    'Morehead St Eagles': "Morehead St.",
    'East Tennessee St Buccaneers': "East Tennessee St.",
    'Tennessee Tech Golden Eagles': "Tennessee Tech",
    'Elon Phoenix': "Elon",
    'USC Trojans': "USC",
    'Long Beach St 49ers': "Long Beach St.",
    'Ole Miss Rebels': "Mississippi",
    'St. Francis (PA) Red Flash': 'Saint Francis',
    'Tennessee St Tigers': "Tennessee St.",
    'Incarnate Word Cardinals': "Incarnate Word",
    'Norfolk St Spartans': "Norfolk St.",
    'Lindenwood Lions': 'Lindenwood',
    'Albany Great Danes': "Albany",
    'Bowling Green Falcons': 'Bowling Green',
    'Temple Owls': "Temple",
    'UIC Flames': "Illinois Chicago",
    'Western Michigan Broncos': 'Western Michigan',
    'Notre Dame Fighting Irish': "Notre Dame",
    'Georgetown Hoyas': 'Georgetown',
    'Eastern Michigan Eagles': 'Eastern Michigan',
    'Western Kentucky Hilltoppers': 'Western Kentucky',
    'Austin Peay Governors': 'Austin Peay',
    'Samford Bulldogs': 'Samford',
    'UCLA Bruins': 'UCLA',
    'Bellarmine Knights': 'Bellarmine',
    'Chicago St Cougars': 'Chicago St.',
    'South Florida Bulls': 'South Florida',
    'Murray St Racers': 'Murray St.',
    'Delaware Blue Hens': 'Delaware',
    'Loyola Marymount Lions': 'Loyola Marymount',
    'UT-Arlington Mavericks': 'UT Arlington',
    'Georgia Bulldogs': 'Georgia',
    'Charleston Southern Buccaneers': 'Charleston Southern',
    'George Mason Patriots': 'George Mason',
    'Virginia Cavaliers': 'Virginia',
    'Auburn Tigers': "Auburn",
    'Longwood Lancers': "Longwood",
    'McNeese Cowboys': "McNeese St.",
    'Stanford Cardinal': "Stanford",
    'Texas Southern Tigers': "Texas Southern",
    'Howard Bison': 'Howard',
    'Oral Roberts Golden Eagles': 'Oral Roberts',
    'UL Monroe Warhawks': 'Louisiana Monroe',
    'Cincinnati Bearcats': 'Cincinnati',
    'Wichita St Shockers': 'Wichita St.',
    'Xavier Musketeers': "Xavier",
    'Winthrop Eagles': "Winthrop",
    'Florida St Seminoles': 'Florida St.',
    'Georgia St Panthers': 'Georgia St.',
    'North Dakota Fighting Hawks': 'North Dakota',
    'Wyoming Cowboys': 'Wyoming',
    'Weber State Wildcats': 'Weber St.',
    'UC Irvine Anteaters': 'UC Irvine',
    'South Dakota Coyotes': 'South Dakota',
    'Stetson Hatters': 'Stetson',
    'UTSA Roadrunners': 'UTSA',
    'UTEP Miners': 'UTEP',
    'Montana Grizzlies': 'Montana',
    'Delaware St Hornets': 'Delaware St.',
    'Michigan St Spartans': 'Michigan St.',
    'Tenn-Martin Skyhawks': 'Tennessee Martin',
    'Tarleton State Texans': 'Tarleton St.',
    'Jacksonville St Gamecocks': 'Jacksonville St.',
    'UC San Diego Tritons': 'UC San Diego',
    'Portland St Vikings': 'Portland St.',
    'Lamar Cardinals': 'Lamar',
    'Cal Poly Mustangs': 'Cal Poly',
    'Alabama St Hornets': 'Alabama St.',
    'Chattanooga Mocs': 'Chattanooga',
    'James Madison Dukes': 'James Madison',
    "Florida Int'l Golden Panthers":  "FIU",
    'Furman Paladins': 'Furman',
    'Wright St Raiders': 'Wright St.',
    'Stephen F. Austin Lumberjacks': 'Stephen F. Austin',
    'Missouri St Bears': 'Missouri St.',
    'CSU Bakersfield Roadrunners': 'Cal St. Bakersfield',
    'Hampton Pirates': 'Hampton',
    'The Citadel Bulldogs': 'The Citadel',
    'Merrimack Warriors': 'Merrimack',
    'Queens University Royals': 'Queens',
    'New Mexico St Aggies': 'New Mexico St.',
    'Miss Valley St Delta Devils': 'Mississippi Valley St.',
    'Nicholls St Colonels': 'Nicholls St.',
    'CSU Northridge Matadors': 'Cal St. Northridge',
    'Middle Tennessee Blue Raiders': 'Middle Tennessee',
    'Villanova Wildcats': 'Villanova',
    'Western Illinois Leathernecks': 'Western Illinois',
    'East Carolina Pirates': 'East Carolina',
    'N Colorado Bears': 'Northern Colorado',
    'Bradley Braves': 'Bradley',
    'Texas State Bobcats': 'Texas St.',
    'SE Missouri St Redhawks': 'Southeast Missouri St.',
    'Oregon Ducks': 'Oregon',
    "Hawai'i Rainbow Warriors": 'Hawaii',
    'Grambling St Tigers': 'Grambling St.',
    'Bucknell Bison': 'Bucknell'
}


def reprint_dict():
    print("TEAMS_DICT = {")
    for key, value in TEAMS_DICT.items():
        print(f'\t"{key}":"{value}",')
    print("}")

    print(362 - len(TEAMS_DICT))
